### ISSUE TITLE
Build fails on PostgreSQL 16.8 due to removed SysScanDesc and systable_beginscan() APIs

### ISSUE THREAD

**Issue by abuzarkamal** [HexaCluster/credcheck#50]
Hello Maintainer, 

The extension fails to compile on PostgreSQL 16.8 because SysScanDesc and systable_beginscan() were removed in recent PostgreSQL versions. Please fix this ASAP.

Observed error during make:

make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -fvisibility=hidden -Wno-ignored-attributes -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal  -D_GNU_SOURCE -I/usr/include/libxml2   -c -o credcheck.o credcheck.c
credcheck.c: In function ‘set_force_change_password’:
credcheck.c:2600:2: error: unknown type name ‘SysScanDesc’; did you mean ‘HeapScanDesc’?
  SysScanDesc scan;
  ^~~~~~~~~~~
  HeapScanDesc
credcheck.c:2613:9: warning: implicit declaration of function ‘systable_beginscan’; did you mean ‘table_beginscan’? [-Wimplicit-function-declaration]
  scan = systable_beginscan(rel, DbRoleSettingDatidRolidIndexId, true,
         ^~~~~~~~~~~~~~~~~~
         table_beginscan
credcheck.c:2636:2: warning: implicit declaration of function ‘systable_endscan’; did you mean ‘table_endscan’? [-Wimplicit-function-declaration]
  systable_endscan(scan);
  ^~~~~~~~~~~~~~~~
  table_endscan
credcheck.c: In function ‘reset_force_change_password’:
credcheck.c:2651:2: error: unknown type name ‘SysScanDesc’; did you mean ‘HeapScanDesc’?
  SysScanDesc scan;
  ^~~~~~~~~~~
  HeapScanDesc
credcheck.c:2676:10: warning: implicit declaration of function ‘systable_getnext’; did you mean ‘heap_getnext’? [-Wimplicit-function-declaration]
  tuple = systable_getnext(scan);
          ^~~~~~~~~~~~~~~~
          heap_getnext
credcheck.c:2676:8: warning: assignment to ‘HeapTuple’ {aka ‘struct HeapTupleData *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  tuple = systable_getnext(scan);
        ^
make: *** [<builtin>: credcheck.o] Error 1

**Comment by devrimgunduz** [comment]
This also affects 4.0 release. They cannot be build for PostgreSQL 13 to 16.

**Comment by darold** [comment]
It should be fixed by commit 36d45a62 but there's still issues with version < 17 because of the event trigger. Working on it.
